server:
  port: 1
spring:
  application:
    name: conf-dev
  cloud:
    config:
      label: master
      uri: http://localhost:8077
#  datasource:
#    url: jdbc:mysql://192.168.3.168:3306/cloud_platform_user?useUnicode=true&characterEncoding=utf-8&useSSL=true&useTimezone=true&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${random.int}
    hostname: ${spring.cloud.client.ip-address}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
